// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQ96ZYGQo_2oggTwrDTDoecvPBBaPrVeQ',
    appId: '1:1029643146658:web:c263cae73bfcdc12d8cefb',
    messagingSenderId: '1029643146658',
    projectId: 'mentalhealthapp-6c058',
    authDomain: 'mentalhealthapp-6c058.firebaseapp.com',
    storageBucket: 'mentalhealthapp-6c058.appspot.com',
    measurementId: 'G-0TXR511KZL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAl4PkWOJRR8u54lr-V3TKtnBjmhKUrUJ8',
    appId: '1:1029643146658:android:bb66663093530a76d8cefb',
    messagingSenderId: '1029643146658',
    projectId: 'mentalhealthapp-6c058',
    storageBucket: 'mentalhealthapp-6c058.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgRryNicxiMGbD2RTlzYRukMUAHgaG_jA',
    appId: '1:1029643146658:ios:71795df625d31ec3d8cefb',
    messagingSenderId: '1029643146658',
    projectId: 'mentalhealthapp-6c058',
    storageBucket: 'mentalhealthapp-6c058.appspot.com',
    iosBundleId: 'com.example.mentalHealthApp',
  );
}
